sudo: false

language: php

git:
  depth: 5

php:
#  - 5.5
  - 5.6
  - 7.0
#  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"

before_install:
  - if [[ $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction

script: php ./bin/phpunit -c app/phpunit.xml.dist
